### ISSUE TITLE
Changing .scss files does not change page CSS, even on recompile

### ISSUE THREAD

**Issue by theseanco** [brainhubeu/gatsby-docs-kit#5]
I'm trying to change `src/layouts/codeBlock.scss` to remove some margins, but doing this does not change the css changed on the page even after a recompile. I assume the sass needs recompiling, but this doesn't appear to be happening when I run `yarn develop`.

**Comment by damian-brainhub** [comment]
Hi @theseanco 

Thank you for reporting this issue. Currently, we are swamped with work, but we will add it to our roadmap. Are the other `scss` files affected as well by this issue? If so, could you try deleting all `css` files from build folder and then recompile sass once again?

**Comment by theseanco** [comment]
Hi @damian-brainhub  

No worries, thanks for your reply!

The `scss` files within `docs-www/pages` (I am running `yarn develop` within `docs-www`) recompile fine, but those within the parent direcory do not. 

I deleted the `css` files within the `public` folder (I can't find a folder called `build`), but this has made no difference when I run `yarn develop`, but i'm not sure whether `yarn develop` is actually recompiling the sass or not.

Running `npm run build` after deleting the `css` files in the `public` folder doesn't seem to work either.

**Comment by piotr-s-brainhub** [comment]
@theseanco 

do you still encounter this issue?

**Comment by theseanco** [comment]
@piotr-s-brainhub I haven't checked in a long time, if it's only me experiencing this I'd be willing to bet it was user error. Happy to close the issue.

**Comment by piotr-s-brainhub** [comment]
thanks @theseanco 

so I close this issue
