### ISSUE TITLE
Any plan to upgrade gatsby to V2?

### ISSUE THREAD

**Issue by blling** [brainhubeu/gatsby-docs-kit#6]
Any plan to upgrade gatsby to V2?

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by piotr-s-brainhub** [comment]
@blling 

now `@brainhubeu/gatsby-docs-kit` uses gatsby@2
